const projectsData = [
  {
    name: "bwid",
    description: "A geolocalized restaurant search startup",
    pitch: "My first entrepreneurship adventure",
    role: "Main role was Co-Founder",
    link: "http://getbwid.com",
    previewImgUrl: "img/projects/bwid_startup.png",
    goal: "Build an app that could help people find new places to eat",
    skills: "Management, Planning, Development",
    techStack: "Python,Javascript,Django,Angularjs,Objective-C,Swift,Git,Postgresql",
    bigDescription: "<p class='description justified'>I was first contacted as a freelancer to build this app/platform but after a few meetings I was offered the position of technical co-founder. That is how my entrepreneurship journey began. It was a lot of ups and downs from launching the app, receiving media attention, participating in startup competitions (being finalist in some), merging the company with a bigger company and leaving. This is definitely one of the most exciting experiences I had so far. </p>        <p class='description justified'>One of the problems we are facing is the routine, for instance, I always go to the same two or three restaurant everytime, not because there's no other option but because I don't have a quick and reliable way to find out new places to eat. Here's another problem everybody have: Deciding where to go for dinner. Tell me you never asked your partner where he/she want's to go for dinner and he/she responded: 'You pick' and you go back and forth until you so tired you decided to get pizza.</p>",
  },
  {
    name: "bwid iOS",
    description: "An iPhone app",
    pitch: "Built with objective-c on xCode",
    role: "Main role was iOS Developer",
    link: "https://itunes.apple.com/us/app/bwid-restaurantes-abertos/id905148403?mt=8",
    previewImgUrl: "img/projects/bwid_app.png",
    goal: "Build an app achieve the startup goal",
    skills: "Planning, Development",
    techStack: "Objective-C, Git, xCode",
    bigDescription: "<p class='description justified'>The main product of the startup is this iOS app where the user can search for restaurants nearby, the restaurants are offered in form of cards where the users can swipe left to see a new one or swipe right to see more information about the desired restaurant.</p><p class='description justified'>In the restaurant details screen the user find usefull information to choose the restaurant or not. Such information can be: distance from the user location, average meal price, free wifi, handcap capable, friends who like and the most important the user can see a map to find where the restaurant are and ask for a route if necessary.</p>",
  },
  {
    name: "bwid web",
    description: "The restaurant control panel",
    pitch: "Built with AngularJS",
    role: "Main role was Software Engineer",
    link: "http://cp.getbwid.com",
    previewImgUrl: "img/projects/bwid_web_cp.png",
    goal: "Offer a personalized platform for the restaurant edit their information",
    skills: "Development",
    techStack: "Html,Css,AngularJS,Fullstack Development",
    bigDescription: "<p class='description justified'>All the restaurant information is curated but we also offer a website where the restaurant owner can update his information keeping updated all the time. For restaurant that uses our custom app they can also send push notification from this portal.</p><p class='description justified'>The second most important product in our startup is a widget that can be implemented in any website and allows the restaurant receive reservations online. This portal also allow the owner manage their resevation details such as when start, when ends, which days of the week allow the reservations, block a day like holidays and much more. This portal is integrated with the backend system and updates the widget in real time giving the restaurant owners great control over their operation.</p>",
  },
  {
    name: "Jazz Side",
    description: "A place where dreams come true",
    pitch: "Built with Python, Django, Postgress, JS",
    role: "Main role was Software Engineer",
    link: "http://jazzside.com.br",
    previewImgUrl: "img/projects/jazz_side.png",
    goal: "Create a platform to support a mouth to mouth company",
    skills: "Development",
    techStack: "Python,Django,Javascript,Git,Postgresql,Fullstack Development",
    bigDescription: "<p class='description justified'>One of the my most interesting projects JazzSide was a niche product, the challenge was to add value to a broader audience. To do that we have added more functionality to the web website such as a dining guide where the system suggests restaurants based on the occasion, price, who is going what time and much more. We also included wizards that remove the need for a first contact and speed up the process two times.</p><p class='description justified'>JazzSide is a company that make dreams come true, literally, their clients ask the craziest things and they make it happen. Some examples are: Playing tennis with Andre Agassi or Pete Sampras, being james bond for one night or surf with Kelly Slater. Being a niche market most of the company clients comes from the famous mouth to mouth, our goal was to change that and get more clients from the web.</p>",
  },
  {
    name: "Grão Gourmet",
    description: "Premium coffess delivered every month at your door",
    pitch: "Built with Python, Django, Postgress, JS and Fullstack Developmente",
    role: "Main role was Software Engineer",
    link: "https://www.graogourmet.com/",
    previewImgUrl: "img/projects/graogourmet.png",
    goal: "Build the company's first website that works for both subscription and the online store",
    skills: "Development",
    techStack: "Python,Django,Javascript,Git,Postgresql,AngularJS",
    bigDescription: "<p class='description justified'>Because they were just starting they didn't have a clear vision about the product so communication was key to deliver a excellent product that last for years. At the time of creation there was not a solution that meet all their requirements so we built from the ground up the whole platform, including the subscription, e-commerce store, content pages, payment and shipping integrations.</p><p class='description justified'>Grao Gourmet works in a very different way compared to the big coffee stores in Brazil, they offer a very personalized experience at good rates and they really love what they do. The startup is growing fast and getting more and more users every month.</p>",
  },
]

export default projectsData;